version: '3'

services: 
  api-solid-pg:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment: 
    # as variaveis e valores devem ser escritos unidos pela igualdade, 
    # separadas por espaços pode gerar erro
    
      - POSTGRESQL_USERNAME=eduardo
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api-solid

